apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: feature-monitor-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metabase-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
spec:
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      containers:
      - name: metabase
        image: metabase/metabase:latest
        env:
        - name: MB_DB_TYPE
          value: h2
        - name: MB_DB_FILE
          value: /metabase-data/metabase.db
        volumeMounts:
        - name: feature-monitor-storage
          mountPath: /data
        - name: metabase-db-storage
          mountPath: /metabase-data
        ports:
        - containerPort: 3000
      volumes:
      - name: feature-monitor-storage
        persistentVolumeClaim:
          claimName: feature-monitor-pvc
      - name: metabase-db-storage
        persistentVolumeClaim:
          claimName: metabase-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: metabase
spec:
  type: LoadBalancer
  selector:
    app: metabase
  ports:
  - port: 3000
    targetPort: 3000